"use strict";
// Sample object with values
const originalObject = {
    key1: 'value1',
    key2: 'value2',
    key3: 'value3'
};
// Function to generate new keys
function generateNewKey(key) {
    return 'new_' + key;
}
// Create a new object with keys generated by the function
const newObject = Object.fromEntries(Object.entries(originalObject).map(([key, value]) => [generateNewKey(key), value]));
console.log(newObject);
